// excerise 9 DATE: 20/03/2024
// WASEEM AHMED 
// THE FOLLOWING PROGRAM LET YOU PRINT YOUR FAVOURITE NUMBER
var FAVOURITE_NUMBER = "3";
console.log("MY FAVORITE NUMBER IS ".concat(FAVOURITE_NUMBER));
