//QUESTION #5 
/**Famous Quote 2: Repeat Exercise 4, but this time store the famous person’s name in a variable called famous_person. Then compose your message and store it in a new variable called message. Print your message.
 */

let famous_person: string = `"Nietzsche`
let qoute: string = `Those Who Were Seen Dancing Were Thought To Be Insane By Those Who Could Not Hear The Music"`
let message = `${famous_person} once said ${qoute}`;
console.log(message)